### ISSUE TITLE
Coerce incomplete data to full cryopose spec

### ISSUE THREAD

**Issue by alisterburt** [teamtomo/cryotypes#14]
We have the validators @brisvag added, what about coercing by adding missing columns?

**Comment by brisvag** [comment]
Yes!

**Comment by alisterburt** [comment]
closed by #15

**Comment by alisterburt** [comment]
or not? there is some coersion logic in the constructor though, not sure when it was added

**Comment by brisvag** [comment]
Yes, it shoudl be good; if you pass `coerce=True` then you should get a df with all the required columns populated; otherwise, you get an error.
